/* Auto-generated by ESPHome components/duke3d — do not edit by hand.
 * Source: esphome.yaml → duke3d.pico_gamepad_map (`action:` tokens).
 * Used by input.cpp to log which logical button fired (matched SC,... lines).
 */
#pragma once

#include <stdint.h>

static inline const char *pico_uart_gamepad_label_for_scancode(unsigned scancode) {
    switch (scancode) {
        case 27u: return "y";
        case 28u: return "x";
        case 29u: return "a";
        case 30u: return "z";
        case 40u: return "b";
        case 44u: return "c";
        case 56u: return "bumper_l";
        case 57u: return "bumper_r";
        case 90u: return "cross_up";
        case 106u: return "cross_down";
        case 107u: return "cross_left";
        case 108u: return "cross_right";
        default:
            return NULL;
    }
}
