/* Auto-generated by ESPHome components/duke3d — do not edit by hand.
 * Source: esphome.yaml → duke3d.pico_gamepad_map + fixed HID keyboard subset.
 * Pico firmware has no Duke knowledge; regenerate after `esphome compile`.
 */
#pragma once

#include <stdint.h>
#include <string.h>

/* When start.action is record_session: warm-restart random map on ESP + drop HID Escape (pads leak Start as ESC). */
#define PICO_UART_BRIDGE_DROP_HID_KEYBOARD_ESCAPE (1u)

#define PICO_UART_BRIDGE_HID_KEYBOARD_ESCAPE (0x29u)

/* Returned scancode [0..] or negative: -1 → no Duke mapping (ignore).
 * Logical names match vendor decode bitmask → string (YAML pico_gamepad_map keys).
 */
static inline int32_t pico_uart_gp_logical_to_duke_scancode(const char *n) {
    if (!n)
        return -1;
    if (!strcmp(n, "cross_up"))
        return 90;
    if (!strcmp(n, "cross_down"))
        return 106;
    if (!strcmp(n, "cross_left"))
        return 107;
    if (!strcmp(n, "cross_right"))
        return 108;
    if (!strcmp(n, "a"))
        return 29;
    if (!strcmp(n, "b"))
        return 40;
    if (!strcmp(n, "c"))
        return 44;
    if (!strcmp(n, "x"))
        return 28;
    if (!strcmp(n, "y"))
        return 27;
    if (!strcmp(n, "z"))
        return 30;
    if (!strcmp(n, "start"))
        return -1;
    if (!strcmp(n, "bumper_l"))
        return 56;
    if (!strcmp(n, "bumper_r"))
        return 57;
    if (!strcmp(n, "star"))
        return 1;
    if (!strcmp(n, "dash"))
        return -1;
    if (!strcmp(n, "heart"))
        return -1;
    return -1;
}

/* USB HID boot keyboard usage in KB,... second field → Duke scancode or -1 if unmapped */
static inline int32_t pico_uart_hid_keyboard_to_duke_scancode(unsigned hid) {
    switch (hid) {
    case 0x1Au:
        return 17;
    case 0x04u:
        return 30;
    case 0x16u:
        return 31;
    case 0x07u:
        return 32;
    case 0x1Du:
        return 44;
    case 0x52u:
        return 90;
    case 0x51u:
        return 106;
    case 0x50u:
        return 107;
    case 0x4Fu:
        return 108;
    case 0x2Cu:
        return 57;
    case 0x2Bu:
        return 15;
    case 0x28u:
        return 28;
    case 0x29u:
        return 1;
    case 0xE0u:
        return 29;
    default:
        return -1;
    }
}
