/* Auto-generated by ESPHome components/duke3d — do not edit by hand.
 * Source: esphome.yaml → duke3d.pico_gamepad_map (`action:` tokens).
 * Regenerate: esphome compile … or esphome run …
 */
#pragma once

#define PICO_GP_ACT_CROSS_UP (90u)
#define PICO_GP_ACT_CROSS_DOWN (106u)
#define PICO_GP_ACT_CROSS_LEFT (107u)
#define PICO_GP_ACT_CROSS_RIGHT (108u)
#define PICO_GP_ACT_A (29u)
#define PICO_GP_ACT_B (40u)
#define PICO_GP_ACT_C (44u)
#define PICO_GP_ACT_X (28u)
#define PICO_GP_ACT_Y (27u)
#define PICO_GP_ACT_Z (30u)
#define PICO_GP_ACT_START (1u)
#define PICO_GP_ACT_BUMPER_L (56u)
#define PICO_GP_ACT_BUMPER_R (57u)
#define PICO_GP_ACT_STAR (0u)
#define PICO_GP_ACT_DASH (0u)
#define PICO_GP_ACT_HEART (0u)

#define PICO_START_SENDS_RANDOM_DEMO_CMD (0u)
